<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Images</name>
   <tag></tag>
   <elementGuidId>47189378-7a6f-4bdc-9ac9-b525177632dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.b_LinksColorMD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='b-scopeListItem-images']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17486af7-d2b2-4552-bcdf-345364aeb74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b_LinksColorMD</value>
      <webElementGuid>08a88ea6-ad86-4212-880f-b3047b689b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>65665ab7-6640-4cf3-b8c3-3b0d99ee3eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/images/search?q=knight&amp;FORM=HDRSC3</value>
      <webElementGuid>0c7e66ad-9ddd-48c0-a181-9d800f4adc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>h</name>
      <type>Main</type>
      <value>ID=SERP,5032.1</value>
      <webElementGuid>80adda06-4102-48e9-80d9-5f5d75353717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>d1b830f9-8b96-48b7-98b8-6f6c73e72ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Images</value>
      <webElementGuid>76e180fb-8ca1-41b2-8f3f-419c8fb48f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b-scopeListItem-images&quot;)/a[@class=&quot;b_LinksColorMD&quot;]</value>
      <webElementGuid>13e675de-73b1-4926-81aa-7738b3d216d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='b-scopeListItem-images']/a</value>
      <webElementGuid>f608acfe-2c8d-4d3f-902a-784ae4fde734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Images')]</value>
      <webElementGuid>338aed95-ff9c-4a27-82c2-f9459d9b7565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copilot'])[1]/following::a[1]</value>
      <webElementGuid>c6f2453b-365e-4c9b-b39b-8905ab9faa51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::a[2]</value>
      <webElementGuid>0cd9188b-bd72-4ac0-b23c-81009632fd83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Videos'])[1]/preceding::a[1]</value>
      <webElementGuid>567372bc-8e4f-44ed-93ab-5b6b4b42204b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maps'])[1]/preceding::a[2]</value>
      <webElementGuid>238c6cda-6d36-4d04-9e17-c99f5d78a8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Images']/parent::*</value>
      <webElementGuid>4f869203-137b-4238-acf3-89bbdedb7b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/images/search?q=knight&amp;FORM=HDRSC3')]</value>
      <webElementGuid>ffe8e8ae-662d-49bf-adc1-02e02816f250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>7b41a094-feac-42b3-83a7-719284f93091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/images/search?q=knight&amp;FORM=HDRSC3' and (text() = 'Images' or . = 'Images')]</value>
      <webElementGuid>b527f714-9ba0-4702-85e8-3a8852e70bb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
