<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_k</name>
   <tag></tag>
   <elementGuidId>d3bf216c-507e-4f78-bbe2-cc7354b6dbb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sb_form_q</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='sb_form_q']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d794e4ef-edcf-4bd3-9fda-f6098009071b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sb_form_q</value>
      <webElementGuid>61d1638e-5091-4dc8-9b75-ded72ea354c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sb_form_q</value>
      <webElementGuid>cfaef2bd-925c-44b3-a77d-8fe633be786e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>26e380a3-e228-46b0-9ee7-04362decd8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b30d023d-c19c-4fda-8d1c-b52757a4b12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>244d7be6-fc45-43e9-80b1-39aba00ba0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>2deb2451-76be-48c5-b772-510dbfe47eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bd75a48f-2a5d-4e49-85e5-31932acf7a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>0b34acaa-b644-440d-8334-6e9721f96e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search the web</value>
      <webElementGuid>98c329b4-f442-4ee6-9113-5b642d5e73a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>457fba73-f3d3-4550-b57b-89ba32007fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6ea9b6a0-e0b6-41fc-bf8a-cb137e5b2d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>1d07def1-7d92-4ee9-896d-6d94c211723d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>deb6512b-80fb-44d5-8826-24148d876a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enterkeyhint</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>3b352ccc-4adf-4395-a25d-76acac92f832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bm</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>a1f2eacf-a827-43bf-a098-8dd5faaec32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>k</value>
      <webElementGuid>9fb3a794-7061-4ef2-8f09-425fd62067b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sb_form_q&quot;)</value>
      <webElementGuid>d33c518d-7e7a-4b8b-9bcc-17fd288a7a9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='sb_form_q']</value>
      <webElementGuid>96cb9fa7-fb7a-4df7-a7eb-99457e3c8a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sb_form_c']/div/textarea</value>
      <webElementGuid>ff94c6f0-2377-4ef4-8b3e-7bcac82bf801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rewards'])[1]/following::textarea[1]</value>
      <webElementGuid>3e43b994-d141-43ef-9a96-310460a5e2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::textarea[1]</value>
      <webElementGuid>5d3d3acd-e174-4dcd-9720-4a6f83a89b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Visual Search'])[1]/preceding::textarea[1]</value>
      <webElementGuid>6c2f5231-7b40-4a75-852d-6ca80a273515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search with a picture instead of text'])[1]/preceding::textarea[1]</value>
      <webElementGuid>127da5e5-70da-4215-8667-9985cca1b3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='k']/parent::*</value>
      <webElementGuid>22b16f81-0611-4fd9-a975-1e56e158a729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c3368a29-ba5e-49d7-acbb-78d14213e0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'sb_form_q' and @name = 'q' and @type = 'search' and @placeholder = 'Search the web' and (text() = 'k' or . = 'k')]</value>
      <webElementGuid>305e4731-b171-445d-a538-aa2710e53524</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
